### ISSUE TITLE
input/output as matrix instead of path to file

### ISSUE THREAD

**Issue by zji90** [jingshuw/SAVERX#1]
Hi,
Is it possible to set the input and output as matrices within R environment instead of path to file, just like SAVER? I'd like to incorporate SAVERX as part of a pipeline in the future and path to file is quite inconvenient.
Thanks!

**Comment by jingshuw** [comment]
Thanks for asking. I can add this option in the coming month.

**Comment by jingshuw** [comment]
This feature is added in the new version of SAVER-X (Version 1.0.0)
