### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by jhu99** [jingshuw/SAVERX#10]
Error in py_module_import(module, convert = convert) : 
  AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

sctransfter was successfully installed, together with tensorflow 2.0.0

**Comment by jingshuw** [comment]
Tensorflow 2.0.0 do have a get_default_graph attribute, see here: https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/get_default_graph
Can you provide a more detailed error message?

**Comment by jingshuw** [comment]
Hi, I did not find where I use this attribute, maybe it is used via some function in some other dependent package, could you give me more details of the error message or the full error message?

**Comment by jhu99** [comment]
Thanks for your reply!
The problem was fixed after creating a new virtual environment and install sctransfter. Maybe the tensorflow version wasn't right in the old environment.
