### ISSUE TITLE
Error in py_get_attr_impl(x, name, silent) :   AttributeError: 'AxisArrays' object has no attribute 'X_dca'

### ISSUE THREAD

**Issue by jhu99** [jingshuw/SAVERX#11]
I got a similar error with an issue posted previously.
Error in py_get_attr_impl(x, name, silent) :   AttributeError: 'AxisArrays' object has no attribute 'X_dca'

Have you get solution for this?

**Comment by jingshuw** [comment]
The error is solved by updating the reticulate R package to version 1.13. Older versions seem to be incomparable with tensorflow 2.0
