### ISSUE TITLE
CreateSeuratObject ISSUE

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [jingshuw/SAVERX#12]
Hi,
thanks for have developed thi interesting tool. I have done the denoising of my data (30k cells),now i want create my seurat object but i encountered thi issue:

![image](https://user-images.githubusercontent.com/53559811/69252133-d4c53680-0bb2-11ea-91d0-979dc9de96df.png)

I think that my output data are denoised correctly without any error (but i'm not sure):

![image](https://user-images.githubusercontent.com/53559811/69252253-ff16f400-0bb2-11ea-9f99-0c07410fdf4a.png)

Have you any suggestion?

Best,
Domenico

**Comment by jingshuw** [comment]
Seems that the cells (columns) don't have names. Can you check if your data.input_s1 has column names?
