### ISSUE TITLE
build users' own pretrained model

### ISSUE THREAD

**Issue by zji90** [jingshuw/SAVERX#9]
Hi,
Just wondering whether it's possible for users to build their own pretrained model, if the scRNA-seq comes from a cell type not included in the current pretrained model provided by saver-x (for example, HEK293t and Jurkat cell lines)? The corresponding bulk RNA-seq data are available.
Thanks!

**Comment by jingshuw** [comment]
Thanks for your suggestion. We will add such a feature in our future main update.
